site_name: osx-wiki
docs_dir : ./docs
use_directory_urls: true
theme: readthedocs
markdown_extensions:
    - smarty
    - attr_list
    - smarty
    - toc:
        permalink: True
        separator: "_"
pages:
    - INDEX: 
        - 'index': 'index.md'
        - 'osx-wiki': 'README.md'
        - 'mysql': 'mysql.md'
        - 'mono': 'mono.md'      
    - Docker:        
        - 'mkdocs': 'docker/index.md'
        - 'swarm': 'docker/swarm.md'
        - 'driver': 'docker/docker-driver.md'
        - 'aspnetcore': 'docker/dotnetsrc.md'
        - 'cloud': 'docker/dockercloud.md'
        - 'chrome': 'docker/chrome.md'
    - git:
        - 'git': 'git/git.md'
    - macOS:        
        - 'brew': 'osx/brew.md'
    - Debian:
        - 'ipaddr': 'debian/ipaddr.md'        
    - Windows:
        - 'Setup Windows10': 'windows/README.md'
        - 'powershell': 'windows/powershell.md'
    - Dotnet:
        - 'wiki': 'dotnet/dotnet.md'
        - '.csproj sdk': 'dotnet/csprojsdk.md'
    - Php:
        - 'hhwm': 'php/hhwm.md'